// ============================================================================
//  version.js — single source of truth for the app version.
//  No build step, so BUMP THESE BY HAND on each deploy (keep roughly in step
//  with the git history). Shown in Settings ▸ About and logged on boot, so you
//  can confirm which deployed build the browser actually loaded.
//    major.minor.patch — minor tracks a shipped phase, patch a fix/tweak.
// ============================================================================
export const APP_VERSION = "2.3.0";  // 2.3.0 = project links survive Emma's pending→posted churn. When a pending txn posts, Emma re-issues a NEW id/merchant/date (only the amount is stable) → the old link orphaned + the posted txn sat unlinked in General (double-count: project line AND General). Two-tier fix in projects.js: (Tier 1) linkTransactionsToItem drops an orphaned same-item/same-amount twin (id no longer in feed) when you link the posted version, so re-linking MOVES rather than duplicates. (Tier 2) healProjectLinks(feed) runs on every real feed load (new onFeedLoaded hook in emma.js — callback, no import cycle): re-points an orphan to its posted twin (exact amount, ≤5 days, unambiguous) or drops it when a live twin is already linked to the same item. No migration; DB writes emit()→repaint. Also carries 2.2.1.
// 2.2.1 = project-linked payments no longer read as "needs a category". uncategorisedHtml (spending.js) + uncatCard (home.js) now skip any txn whose synthKey is in project_item_txns — a payment allocated to a project line item was still surfacing in the "needs a category" prompt (Uncategorised merchant like SOUTHERN SHEDS), even though the forecast/month-panel Projects carve-outs already excluded it. Presentation-only; no schema/engine change.
// 2.2.0 = LifeOS "This month" is now spend-vs-budget. js/lifeos.js enriches the month-net signal with discretionary spend so far (General Expenses via reconcileMonth over the Emma feed) vs the monthly budget (forecast_budgets[GENERAL]) — published as value=spent + trend=budget + pace-aware state (over→bad, ahead-of-straight-line-pace→warn, else good). LifeOS renders it as a progress/pace tile. "Projected cash" unchanged. Fire-and-forget; feed unavailable → budget-only tile.
// 2.1.0 = LifeOS adapter. New js/lifeos.js publishes headline metrics (this-month net + projected cash, forecast-derived) into the shared lifeos.signals table on boot (fire-and-forget), so the new LifeOS hub app can surface them. No schema change to house_project; writes to the separate `lifeos` schema. Later: enrich with Emma actual-vs-forecast + emit task/nudge signals (e.g. stale balances).
// 2.0.0 = V2 milestone. Closes the V2 rework batch (Sessions 16–24): data-driven nav + hash router, Home dashboard (This month / Forecast / Spending / Projects), routed Projects pages + detail, Merchants + Reports + Analysis (merchant-level Keep/Review/Kill) screens, page-ified Settings + Categories, projects simplified (spend timing from line-item due months; no status/priority/category/duration), and the Home snapshot + mobile-chart + Home-coherence fixes. Same stack/schema lineage as 1.x — a marketing/milestone major bump, not a rewrite.
// 1.30.2 = Home Forecast tile reframed to answer one question ("does cash dip below the buffer, and when?"). Leads with the forecast LOW POINT (not "cash now" — today's balance isn't the forecast) + a buffer verdict: big = "£X lowest", meta = "next N mo", sub = "Stays above your £Y buffer · {month}" (or coral "Dips below your £Y buffer in {month}"; big goes coral too). Spark chart kept. Removed the "cash now" headline + the tight-today wording from 1.30.1. New .hp-big .neg CSS.
// 1.30.1 = Home fixes. (1) Spending pillar showed £0 — it filtered on monthOf(t.date) but t.date is the raw "M/D/YYYY" string while monthOf expects the yyyymmdd int (t.dateInt) → every txn NaN'd out; fixed + dropped the misleading total-spend-vs-General-budget bar (now plain total counting spend + biggest category). (2) "This month" card reframed from net-so-far (compared partial actuals to a full-month forecast → always misleadingly negative early-month) to DISCRETIONARY General Expenses spend vs budget (within/over tag, £ left, biggest category) — the number the household actually steers. (3) Forecast pillar wording: cash-now can be BELOW buffer while the forecast low point is ABOVE it (income lands first), which read as contradictory — now says "Below your £X buffer now — income lifts you back above · low £Y in {month}". Engine unchanged/correct (the big July net is Christine's confirmed £14k bonus; Sep dip is the £17k car-payment life event). 228 tests green.
// 1.30.0 = V2 rework batch: bigger/legible mobile Forecast chart. buildChart now uses a NARROWER/TALLER viewBox on mobile (380×300 vs desktop 720×300) so the fixed-viewBox SVG scales UP — a taller plot and ~1.9× larger text on a phone (was tiny under the 720-wide desktop viewBox). Fewer x-labels on mobile (n/4 vs n/6), a small mobile font bump on .ax-lbl/.cf-co-* (viewBox units, compounds with the smaller viewBox), and a matchMedia(max-width:640px) 'change' listener re-renders on breakpoint cross (rotation/resize) — fires only on the crossing, so no thrash / no draw-on replay. UI-only; 228 tests still green.
// 1.29.0 = V2 rework batch: Home snapshot. home.js gained a "This month" strip (actual-vs-forecast: reconcileMonth income/spend/projects net vs engine months[0].net, mint/amber/coral on-track tag; forecast-only line before the Emma feed lands so there's no empty/flash state) and a "needs a category" action card (top-3 unmapped counting merchants with one-tap accept-guess chips via guessCategory+saveCategoryRule; "See all" routes to Spending). Fixed the Spending pillar pre-feed flash — loadEmma now renders the loading state on mount instead of showing "Tap to view spending" while the feed is in flight. Presentation-only; 228 tests still green.
// 1.28.0 = Decision reworked to MERCHANT level. Keep/Review/Kill now lives per-merchant on category_rules.decision (migration 20260714130000 + store.saveMerchantDecision) — NOT per-category or per-flow. Analysis (#/analysis) is now a pure merchant triage: every merchant with spend in the 3/6/12/All window, grouped Kill/Review/Undecided(top 40 by spend)/Keep, inline decision setter, drill to the merchant graph; hitting Keep drops it off the triage (collapsed pile). REMOVED: the per-category decision <select> from the Categories manager, the Keep/Review/Kill control from the Finances flow sheet, and the whole "Cost to kill" section from Reports. Stale columns categories.decision + recurring_flows.decision now UNUSED (non-destructive). Presentation-only; 228 tests still green.
// 1.27.0 = V2 rework batch C: Reports + NEW Analysis screen. A Keep/Review/Kill "decision" now lived on BOTH fixed commitments (recurring_flows.decision) and variable buckets (categories.decision) — migration 20260714120000. [SUPERSEDED by 1.28.0 — decision moved to merchant level.] NEW #/analysis screen (Spend group, js/analysis.js) + exported merchantDetailHtml from Merchants; Reports category drill shows that same merchant-detail graph.
// 1.26.0 = V2 rework batch B: Projects simplified. Projects lose status/priority/category/duration entirely. Spend TIMING now comes from each line item's due_month (store.currentForecast derives a cost_spread from due months; item w/o due → project start; no items → whole cost spikes at start). Engine: plannedCostInMonth drops duration/even-split; no status filter — a project stays in the forecast for its REMAINING cost (est−act) and shrinks to £0 once linked txns cover it. Actuals ONLY via linked transactions (manual actual field gone); line-item status is DERIVED To pay/Paid (itemPaid). Cost-spread editor removed. Tasks sub-view reworked to derived status + link-through. tests/engine.tests.js updated (91 assertions; 228 total green).
// 1.25.0 = V2 rework batch A: Settings is now a routed #/settings PAGE (header gear removed; Scenarios + the Salaries editor + Trading 212 dropped; the "General Expenses" monthly budget moved here from the Spending category manager). NEW Categories page (#/categories, Set up group, js/categories-page.js) — the category manager (counts-as-spend toggles + move/merge/delete + add) lifted out of the foot of Spending into its own screen. No schema/engine change; 226 tests still green.
// 1.24.0 = V2 step 4: Reports / Budgeting page (js/reports.js). Category trends over a rolling 3/6/12/All-month window (month-on-month change vs the prior equal period + sparkline + a monthly-total bar chart), sortable Biggest/Movers, tap a category → its ranked merchants (via rankMerchants) → re-file through the shared Spending sheet. Plus a "Cost to kill" list: every expense recurring_flow annualised (frequency/interval-aware), biggest £/yr first. PURE cores reportCategories + annualCost; tests/reports.tests.js (32 assertions; 226 total green). Reuses the memoised Emma feed + shared category logic. No schema/engine change. (js/reports.js). Category trends over a rolling 3/6/12/All-month window (month-on-month change vs the prior equal period + sparkline + a monthly-total bar chart), sortable Biggest/Movers, tap a category → its ranked merchants (via rankMerchants) → re-file through the shared Spending sheet. Plus a "Cost to kill" list: every expense recurring_flow annualised (frequency/interval-aware), biggest £/yr first. PURE cores reportCategories + annualCost; tests/reports.tests.js (32 assertions; 226 total green). Reuses the memoised Emma feed + shared category logic. No schema/engine change.
// 1.23.0 = V2 step 3: Merchants page (js/merchants.js). Two views — "Merchants" (ranked by spend over a 3/6/12/All-month window, month-on-month change vs the prior equal period, a sparkline, category filter + search; tap → per-merchant detail with monthly bars + its transactions) and "All transactions" (the filterable/sortable full-feed browser that supersedes Spending's search). Re-uses the memoised Emma feed + shared category logic; re-filing opens the SAME Spending categorise sheet (now exported, feed passed in). Pure `rankMerchants` core + tests/merchants.tests.js (22 assertions; 194 total green). No schema/engine change.
// 1.22.0 = V2 step 2: Projects rework. Projects are now PAGES not pop-ups — tapping a project routes to #/projects/:id (js/project-detail.js): header + stat tiles (Budget/Spent/Remaining/Affordability), an "across the build" month track (line items on the month axis via the new project_items.due_month + planned-vs-actual bars), recent linked payments, and the reused line-items/budget/cost-spread block. The Projects TAB is now a dashboard (committed/spent + a funded bar vs available cash, cards with spend-progress). The old Tasks tab folded IN as a "Tasks" sub-view toggle of the Projects screen (removed from nav). Migration: project_items.due_month.
// 1.21.1 = project-linking fixes: (1) transaction-side "Add to project" now lists each of a merchant's payments with a per-payment Link/Move (pick the single £531 B&Q, not all B&Q); optional "link all unlinked". (2) A payment already linked to another project/item is no longer hidden — it shows where it sits and linking MOVES it (both surfaces: Spending categorise sheet + line-item search). (3) Moving a payment recomputes BOTH the source and target item actual_cost (was leaving the source overstated). // 1.21.0 = V2 step 1: navigation + routing rework. New Home dashboard (three equal pillars — Forecast/Spending/Projects — each taps through), regrouped nav (Home + Plan/Spend/Set up) driven by one definition, mobile bottom nav (Home·Forecast·Spending·Projects) + a "More" grouped drawer, hash-based router (back button works; sub-route slot ready for project detail). Reports + Merchants added as stub screens. Tasks temporarily lives under Plan until it folds into Projects (step 2).
export const BUILD_DATE  = "2026-07-15";
