// ============================================================================
//  version.js — single source of truth for the app version.
//  No build step, so BUMP THESE BY HAND on each deploy (keep roughly in step
//  with the git history). Shown in Settings ▸ About and logged on boot, so you
//  can confirm which deployed build the browser actually loaded.
//    major.minor.patch — minor tracks a shipped phase, patch a fix/tweak.
// ============================================================================
export const APP_VERSION = "1.23.0";  // 1.23.0 = V2 step 3: Merchants page (js/merchants.js). Two views — "Merchants" (ranked by spend over a 3/6/12/All-month window, month-on-month change vs the prior equal period, a sparkline, category filter + search; tap → per-merchant detail with monthly bars + its transactions) and "All transactions" (the filterable/sortable full-feed browser that supersedes Spending's search). Re-uses the memoised Emma feed + shared category logic; re-filing opens the SAME Spending categorise sheet (now exported, feed passed in). Pure `rankMerchants` core + tests/merchants.tests.js (22 assertions; 194 total green). No schema/engine change.
// 1.22.0 = V2 step 2: Projects rework. Projects are now PAGES not pop-ups — tapping a project routes to #/projects/:id (js/project-detail.js): header + stat tiles (Budget/Spent/Remaining/Affordability), an "across the build" month track (line items on the month axis via the new project_items.due_month + planned-vs-actual bars), recent linked payments, and the reused line-items/budget/cost-spread block. The Projects TAB is now a dashboard (committed/spent + a funded bar vs available cash, cards with spend-progress). The old Tasks tab folded IN as a "Tasks" sub-view toggle of the Projects screen (removed from nav). Migration: project_items.due_month.
// 1.21.1 = project-linking fixes: (1) transaction-side "Add to project" now lists each of a merchant's payments with a per-payment Link/Move (pick the single £531 B&Q, not all B&Q); optional "link all unlinked". (2) A payment already linked to another project/item is no longer hidden — it shows where it sits and linking MOVES it (both surfaces: Spending categorise sheet + line-item search). (3) Moving a payment recomputes BOTH the source and target item actual_cost (was leaving the source overstated). // 1.21.0 = V2 step 1: navigation + routing rework. New Home dashboard (three equal pillars — Forecast/Spending/Projects — each taps through), regrouped nav (Home + Plan/Spend/Set up) driven by one definition, mobile bottom nav (Home·Forecast·Spending·Projects) + a "More" grouped drawer, hash-based router (back button works; sub-route slot ready for project detail). Reports + Merchants added as stub screens. Tasks temporarily lives under Plan until it folds into Projects (step 2).
export const BUILD_DATE  = "2026-07-13";
